"""empty message

Revision ID: 186bd0b1ee40
Revises: 
Create Date: 2021-12-03 11:53:22.730148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '186bd0b1ee40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lga',
    sa.Column('lga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('lga_name', sa.String(length=55), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('lga_id')
    )
    op.create_table('question',
    sa.Column('q_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.add_column('document', sa.Column('doc_msg', sa.String(length=200), nullable=False))
    op.drop_column('document', 'doc_message')
    op.alter_column('guest', 'profilepix',
               existing_type=mysql.VARCHAR(length=59),
               nullable=False)
    op.drop_constraint('guest_ibfk_1', 'guest', type_='foreignkey')
    op.create_foreign_key(None, 'guest', 'state', ['stateid'], ['state_id'])
    op.add_column('state', sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('state', 'id')
    op.add_column('transaction', sa.Column('trx_ipaddress', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'trx_ipaddress')
    op.add_column('state', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('state', 'state_id')
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.create_foreign_key('guest_ibfk_1', 'guest', 'state', ['stateid'], ['id'])
    op.alter_column('guest', 'profilepix',
               existing_type=mysql.VARCHAR(length=59),
               nullable=True)
    op.add_column('document', sa.Column('doc_message', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('document', 'doc_msg')
    op.drop_table('question')
    op.drop_table('lga')
    # ### end Alembic commands ###
